@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "duyhau1",
  "password": "123456",
  "email": "congtuzxc@gmail.com",
  "avatarColor": "red"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "duyhau",
  "password": "123456"
}

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "congtuzxc@gmail.com"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/0ab09d2213faa51eaffc75c9841c292b0efee2a6
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "1234567",
  "confirmPassword": "1234567"
}
